### ISSUE TITLE
Unable to cancel from Year Months view to Month day view

### ISSUE THREAD

**Issue by igni2017** [mominsamir/smDateTimeRangePicker#139]
From the Custom range, I clicked on Month year on top as show in the snapshot
![d1](https://cloud.githubusercontent.com/assets/26619948/24237479/215cc7ea-0faf-11e7-86a6-432314420e86.png)
It shows the Year and months view as below
![d2](https://cloud.githubusercontent.com/assets/26619948/24237499/3aa2cbd2-0faf-11e7-90f9-6aec88a25470.png)
When I click on cancel it closes the popup but when I select the custom range again it shows the year months view instead of the default view with Month and date.

**Comment by mailmrmanoj** [comment]
+1

**Comment by oscar09** [comment]
Fix has been submitted.

Cancel button will take you back to the 1st selection list. When the "custom range" button is clicked again, the DATE view is displayed instead of the 'YEAR' view. The same behaviour happens when the user clicks outside of the calendar window. I also added a "back to calendar" link which will take you back to the DATE view when the YEAR view is currently active.

Please test and let me know if you find anything.
