### ISSUE TITLE
Information about how we can contribute

### ISSUE THREAD

**Issue by pablorsk** [mominsamir/smDateTimeRangePicker#92]
We need information about how install tools for run this library localy, test, and generate new code (#81).

For example instructions about npm, bower and gulp.

We think:
```bash
npm install
npm install -g bower
bower install
```

but tasks for gulp?

**Comment by oscar09** [comment]
As you pointed out, you need to run those commands 1st and I believe gulp is installed as part of the NPM packages. I already had gulp installed on my machine, that is why I am not sure if you have to do something else in order to install Gulp. But it if does not work for you, check out this page https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

In simple words, Gulp automates the development workflow; it is similar to Grunt. Basically you can create different tasks to run node servers, minify css, uglify js, concat files, etc. All those tasks are defined in gulpfile.js. You won't need to update this file for this project, but you can go through it if you want to find out the different tasks that have been defined so far. In order to contribute with this project you will mostly work with the following 2 tasks:
- "gulp default" It will run a node server and open your browser pointing to the examples for this project. In this page you can test the bugs/enhancements you are working on.
- "gulp build" It will concat the different js files, among other things. This task generates the "picker.js" file that is used for distribution. As stated in our previous discussion, this file is "read only", any change that you want to make must be done on the picker/js/* files. This task is executed after your changes have been tested and you want to submit the pull request.

I hope it helps.

@mominsamir correct me if I said something wrong about the process.

**Comment by pablorsk** [comment]
Thanks a lot @oscar09. 

I add CONTRIBUTING.md to the project #94.
